prooph_event_store:
    stores:
        user_store:
            event_store: Prooph\EventStore\Pdo\MySqlEventStore
            repositories:
                user_collection:
                    repository_class: App\Infrastructure\User\Repository\EventStoreUserCollection
                    aggregate_type: App\Domain\User\User
                    aggregate_translator: prooph_event_sourcing.aggregate_translator

services:
    Prooph\EventStore\EventStore: "@prooph_event_store.user_store"

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator
