prooph_service_bus:
    command_buses:
        user_command_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                type: 'prooph_service_bus.command_bus_router'
    event_buses:
        user_event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                type: 'prooph_service_bus.event_bus_router'

    query_buses:
        read_users_query_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                type: 'prooph_service_bus.query_bus_router'
#services:
#
#    Prooph\ServiceBus\Plugin\MessageProducerPlugin:
#        arguments: ['@Prooph\ServiceBus\Message\Enqueue\EnqueueMessageProducer']
#        tags:
#            - { name: 'prooph_service_bus.event_bus.plugin' }
#
##    Prooph\ServiceBus\Message\Enqueue\EnqueueSerializer:
#
#    Prooph\ServiceBus\Message\Enqueue\EnqueueMessageProducer:
##        factory: ['Prooph\ServiceBus\Message\Enqueue\Container\EnqueueMessageProducerFactory', '__callStatic']
##        arguments: ['enqueue_amqp_message_producer']
#        arguments:
#            $producer: '@Enqueue\Client\ProducerInterface'
#            $serializer: '@Prooph\ServiceBus\Message\Enqueue\EnqueueSerializer'
#            $commandName: 'prooph_bus'
#            $replyTimeout: 2000