prooph_service_bus:
    command_buses:
        user_command_bus: ~
#            router:
#                # Service ID of the async message producer e.g. for Amazon AWS SQS
#                async_switch: 'my_async_message_producer'
#            plugins:
#                - 'async_command_router'
    event_buses:
        user_event_bus: ~

    query_buses:
        read_users_query_bus: ~
