prooph_service_bus:
    command_buses:
        user_command_bus: ~

    event_buses:
        user_event_bus:
            plugins:
                - 'prooph_service_bus.on_event_invoke_strategy'
            router:
                type: 'prooph_service_bus.event_bus_router'
                routes:
                    App\Domain\User\Event\UserWasCreated\UserWasCreatedEvent: [ 'App\Domain\User\Event\UserWasCreated\UserWasCreatedEventHandler' ]
                    App\Domain\User\Event\ChangedEmailAddress\ChangedEmailAddressEvent: [ 'App\Domain\User\Event\ChangedEmailAddress\ChangedEmailAddressEventHandler' ]
    query_buses:
        read_users_query_bus: ~
