version: '3.5'

services:

    db-event-store-postgres:
        image: postgres:10.4
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: dev
            POSTGRES_USER: dev
            POSTGRES_DB: users
        networks:
          - web
          - backend
        labels:
            - "traefik.frontend.rule=Host:${DB_HOSTNAME}"
            - "traefik.port=5432"
            - "traefik.backend.healthcheck.path=/health"
            - "traefik.backend.healthcheck.interval=10s"
        volumes:
            - ./vendor/prooph/pdo-event-store/scripts/postgres:/docker-entrypoint-initdb.d
            - eventstore-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5432"]
            interval: 30s
            timeout: 10s
            retries: 5

    nginx:
        image: prooph/nginx:www
        ports:
            - 10081:10081
            - 10082:10082
        networks:
          - web
          - backend
        labels:
            - "traefik.frontend.rule=Host:${API_HOSTNAME}"
            - "traefik.port=80"
            - "traefik.docker.network=web"
            - "traefik.backend.healthcheck.path=/health"
            - "traefik.backend.healthcheck.interval=10s"
        links:
            - php:php
        volumes:
            - .:/var/www

    php:
        build:
            context: .docker/php
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        volumes:
            - .:/var/www
        networks:
            - backend
        depends_on:
            - db-event-store-postgres
            - message_queue
        environment:
            - PROOPH_ENV=development
            - APP_ENV=dev

    projection_user:
        image: prooph/php:7.2-cli
        volumes:
            - .:/app
        depends_on:
            - db-event-store-postgres
            - message_queue
        networks:
            - backend
        command: php bin/console event-store:projection:run user_projection
        restart: on-failure # https://stackoverflow.com/a/41854997/890826

    message_queue:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
            RABBITMQ_DEFAULT_USER: "admin"
            RABBITMQ_DEFAULT_PASS: "admin"
            RABBITMQ_DEFAULT_VHOST: "/"
        labels:
          - "traefik.frontend.rule=Host:${MESSAGE_QUEUE_HOSTNAME}"
        networks:
            - backend
            - web
        ports:
            - 15672:15672
            - 5672:5672
volumes:
  eventstore-data:
networks:
    web:
        external: true
    backend:
        driver: bridge
        internal: true
