version: '3'

services:

    db_postgres:
        image: postgres:10.4
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: dev
            POSTGRES_USER: dev
            POSTGRES_DB: users
#        networks:
#          - web
#          - backend
        labels:
            - "traefik.frontend.rule=Host:services-db.phishd.test"
            - "traefik.port=5432"
        volumes:
            - ./vendor/prooph/pdo-event-store/scripts/postgres:/docker-entrypoint-initdb.d
            - ./data:/var/lib/postgresql

    nginx:
        image: prooph/nginx:www
        ports:
            - 10081:10081
            - 10082:10082
            - 8080:80
            - 443:443
#        networks:
#          - web
#          - backend
        labels:
            - "traefik.frontend.rule=Host:users-api.phishd.test"
            - "traefik.port=8080"
        links:
            - php:php
        volumes:
            - .:/var/www

    php:
        build:
            context: .docker/php
            dockerfile: Dockerfile.dev
        env_file:
            - ./.env
        volumes:
            - .:/var/www
#        networks:
#            - backend
        depends_on:
            - db_postgres
        environment:
            - PROOPH_ENV=development
            - APP_ENV=dev

    projection_user:
        image: prooph/php:7.2-cli
        volumes:
            - .:/app
        depends_on:
            - db_postgres
#        networks:
#            - backend
        command: php bin/console event-store:projection:run user_projection

#networks:
#    web:
#        external: true
#    backend:
#        driver: bridge
#        internal: true
