<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace App\Application\Query\GetAllUsers;

final class GetAllUsers extends \Prooph\Common\Messaging\Query
{
    use \Prooph\Common\Messaging\PayloadTrait;

    protected $messageName = 'App\Application\Query\User\GetAllUsers\GetAllUsers';

    protected function setPayload(array $payload): void
    {
        $this->payload = $payload;
    }
}
