<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace App\Domain\User\ValueObject;

final class Email
{
    private $email;

    public function __construct(string $email)
    {
        if (filter_var($email, FILTER_VALIDATE_EMAIL) === false) {
            throw new \InvalidArgumentException('Email is not valid');
        }

        $this->email = $email;
    }

    public function email(): string
    {
        return $this->email;
    }

    public function withEmail(string $email): Email
    {
        return new self($email);
    }

    public function toString(): string
    {
        return $this->email;
    }

    public function __toString(): string
    {
        return $this->email;
    }

    public static function fromString(string $email): Email
    {
        return new self($email);
    }
}
