<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace App\Domain\User\Event\ChangedEmailAddress;

use App\Domain\User\UserId;
use App\Domain\User\ValueObject\Auth\Credentials;
use App\Domain\User\ValueObject\Auth\HashedPassword;
use App\Domain\User\ValueObject\Email;

final class ChangedEmailAddressEvent extends \Prooph\EventSourcing\AggregateChanged
{
    protected $messageName = 'App\Domain\User\Event\ChangedEmailAddress\ChangedEmailAddressEvent';

    protected $payload = [];
    /**
     * @var UserId
     */
    private $userId;
    /**
     * @var Email
     */
    private $email;
    /**
     * @var Credentials
     */
    private $credentials;

    public function userId(): \App\Domain\User\UserId
    {
        if (null === $this->userId) {
            $this->userId = \App\Domain\User\UserId::fromString($this->aggregateId());
        }

        return $this->userId;
    }

    public function email(): \App\Domain\User\ValueObject\Email
    {
        if (null === $this->email) {
            $this->email = \App\Domain\User\ValueObject\Email::fromString($this->payload['email']);
        }

        return $this->email;
    }

    public static function with(\App\Domain\User\UserId $userId, \App\Domain\User\ValueObject\Auth\Credentials $credentials): ChangedEmailAddressEvent
    {
        return new self($userId->toString(), [
            'email' => $credentials->email()->toString(),
            'password' => $credentials->email()->toString(),
        ]);
    }

    protected function setPayload(array $payload): void
    {
        if (!isset($payload['email']) || !\is_string($payload['email'])) {
            throw new \InvalidArgumentException("Key 'email' is missing in payload or is not a string");
        }

        $this->payload = $payload;
    }

    public function credentials(): Credentials
    {
        if ($this->credentials === null) {
            $this->credentials = $this->credentials = new Credentials(Email::fromString($this->payload['email']),
                HashedPassword::fromHash($this->payload['password']));;
        }

        return $this->credentials;
    }
}
