#index:
#    path: /
#    controller: App\Controller\DefaultController::index

users_get_all:
    path: /users
    controller: App\UI\Http\Rest\Controller\UsersController::allUsersAction
    methods:    [GET, HEAD]

users_create:
    path: /users
    controller: App\UI\Http\Rest\Controller\UsersController::newUserAction
    methods:    [POST]

users_update:
    path: /users
    controller: App\UI\Http\Rest\Controller\UsersController::updateUserAction
    methods:    [PUT]

users_get_by_id:
    path: /users/{id}
    controller: App\UI\Http\Rest\Controller\UsersController::updateUserAction
    methods:    [GET]
