index:
    path: /
    controller: App\UI\Http\Rest\Controller\DefaultController::indexAction
    methods:    [GET, HEAD]

api_login_check:
    path: /login_check

current_user:
    path: /api/me
    controller: App\UI\Http\Rest\Controller\UsersController::meAction
    methods: [GET]

register:
    path: /register
    controller: App\UI\Http\Rest\Controller\UsersController::newUserAction
    methods:    [POST]

users_get_all:
    path: /api/users
    controller: App\UI\Http\Rest\Controller\UsersController::allUsersAction
    methods:    [GET, HEAD]

users_update:
    path: /api/users/{id}
    controller: App\UI\Http\Rest\Controller\UsersController::updateUserAction
    methods:    [PUT]

users_get_by_id:
    path: /api/users/{id}
    controller: App\UI\Http\Rest\Controller\UsersController::getUserAction
    methods:    [GET]

